article/urls.py
# coding=utf-8
from django.conf.urls import url

from . import views

# set the application namespace so that Django knows which app view
# to create for a url when using the {% url %} template tag.
app_name = 'article'

urlpatterns = [
    # # ex: /polls/
    # url(r'^$', views.home, name='home'),
    # # ex: /polls/5/
    # # Using parentheses around a pattern “captures” the text matched
    # # by that pattern and sends it as an argument to the view function;
    # # ?P<question_id> defines the name that will be used to identify the
    # # matched pattern.
    # url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # # ex: /polls/5/results/
    # url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # # ex: /polls/5/vote/
    # url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'(?P<id>\d+)/$', views.detail, name='detail'),
    url(r'^search/$', views.search_blog, name='search'),
]

my_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import article.views
from my_blog.views import home, archives, search_tag, about_me

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name='home'),
    url(r'^blog/', include('article.urls')),
    url(r'^archives/$', archives, name='archives'),
    url(r'^archives/(?P<name>\w+)/$', search_tag, name='search_tag'),
    url(r'^about_me/$', about_me, name='about_me'),
]

article/models.py
# coding=utf-8
from __future__ import unicode_literals

from django.db import models

# When making model changes, do the follows step-by-step:
# 1. Change your models (in models.py).
# 2. Run python manage.py makemigrations to create migrations for those changes
# 3. Run python manage.py migrate to apply those changes to the database.

# Create your models here.
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Article(models.Model):
    title = models.CharField(max_length=100)

    # To get categories of some article a, use: a.categories.all()/get(pk=1)/add(c)
    # To get articles which are of some category c, use: py.article_set.all()/get(pk=1)
    categories = models.ManyToManyField(Category, verbose_name='categories')

    # auto_now_add=True makes date_time a non-editable field
    date_time = models.DateTimeField('date published')  # (auto_now_add=True)

    content = models.TextField(blank=True, null=True)

    def get_absolute_url(self):
        path = reverse('blog', kwargs={'id': self.id})
        return "http://127.0.0.1:8000%s" % path

    def __str__(self):
        return self.title

    class Meta:
        """
        Give your model metadata by using an inner class Meta.

        Model metadata is “anything that’s not a field”, such as ordering
        options (ordering), database table name (db_table), or human-readable
        singular and plural names (verbose_name and verbose_name_plural).
        None are required, and adding class Meta to a model is completely
        optional.

        """
        ordering = ['-date_time']

article/views.py
from django.http import Http404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

# Create your views here.
from article.models import Article


def detail(request, id):
    post = get_object_or_404(Article, pk=id)
    return render(request, 'post.html', {'post': post})


def search_blog(request):
    """
    Only supports to search (by words in the titles) from the search form.
    Visiting "/blog/search/some_keywords" will be redirected to the home page.

    """
    if "search" in request.GET:
        search_target = request.GET["search"]
        if not search_target:
            return render(request, "home.html")
        else:
            article_set = Article.objects.filter(title__icontains=search_target)
            if (article_set.count() == 0):
                return render(request, 'search.html',
                              {'article_set': article_set,
                               'having_articles': False
                               })
            else:
                return render(request, 'search.html',
                              {'article_set': article_set,
                               'having_articles': True
                               })

    return HttpResponseRedirect("/")

my_blog/views.py
from __future__ import print_function

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import Http404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

# Create your views here.
from article.models import Article, Category

num_posts_per_page = 3


def home(request):
    # Deprecated:
    # post_list = Article.objects.all()
    # return render(request, 'home.html', {'post_list': post_list})

    posts = Article.objects.all()
    # Show 'num_posts_per_page' posts (blogs) per page
    paginator = Paginator(posts, num_posts_per_page)

    # The number of the page to be visited, starting from 1:
    page_number = request.GET.get('page')

    try:
        post_list = paginator.page(page_number)
    except PageNotAnInteger:
        # If page_number is not an integer, deliver first page.
        post_list = paginator.page(1)
    except EmptyPage:
        # If page_number is out of range (e.g. 9999), deliver last page of
        # results.
        post_list = paginator.page(paginator.num_pages)
    return render(request, 'home.html', {'post_list': post_list})


def archives(request):
    try:
        category_list = Category.objects.all()
    except Category.DoesNotExist:
        raise Http404

    try:
        having_articles = (Article.objects.all().count() > 0)
    except Article.DoesNotExist:
        raise Http404

    return render(request, 'archives.html',
                  {'category_list': category_list,
                   'display': "none",
                   'having_articles': having_articles
                   })


def search_tag(request, name):
    try:
        category_list = Category.objects.filter(name__exact=str(name))
    except Category.DoesNotExist:
        raise Http404
    return render(request, 'archives.html',
                  {'category_list': category_list,
                   'display': "block",
                   'having_articles': True
                   })


def about_me(request):
    return render(request, "aboutme.html")

templates/aboutme.html
{% extends "base.html" %}
{% load custom_markdown %}

{% block content %}
    <header class="post-header">
        <h2 class="post-title">About Me</h2>
        <p>
            Constructing...
        </p>
    </header>
{% endblock %}

templates/archives.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    <script src="{% static "jquery.js" %}"></script>
    <script type="text/javascript">
        $(document).ready(
            function () {
                $(".category_flip").click(
                    function () {
                        $(this).next().slideToggle("slow");
                    }
                );
            }
        );
    </script>

    <style type="text/css">
        div.article_list_panel {
            display: {{ display }};
        }
    </style>
{% endblock %}

{% block content %}
    <div class="posts">
        {% if having_articles and category_list and category_list.count %}

            {% for category in category_list %}
                {% if category.article_set.count %}
                    <section class="post">
                        <header class="post-header category_flip">
                            <h2 class="post-title">
                                {{ category.name }}
                            </h2>
                        </header>
                        <div class="article_list_panel">
                            Related Blogs:
                            <div>
                                {% for article in category.article_set.all %}
                                    <div>
                                        <a href="{% url "article:detail" article.id %}">
                                            {{ article.title }}
                                        </a>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </section>
                {% endif %}
            {% endfor %}

        {% else %}
            {% block deal_with_special_cases %}
                {% comment %}
                If category_list is null (happening in search_tag when no such category is
                found, or in archives when there are no categories at all),
                or category_list is not null but is empty (no articles of this category found,
                happening in search_tag),
                or there is no articles at all (given by `having_articles`).
                {% endcomment %}
                <section class="post">
                    <header class="post-header category_flip">
                        <h2 class="post-title">
                            Ah-oh!
                        </h2>
                    </header>
                    <div>
                        No categorie(s) found. :(
                    </div>
                </section>
            {% endblock %}

        {% endif %}
    </div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
{% load static %}
{% load custom_markdown %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A layout example that shows off a blog page with a list of posts.">

    <title>{% block title %}Psrit's Blog{% endblock %}</title>
    <link rel="stylesheet" href="{% static "pure.css" %}">
    <link rel="stylesheet" href="{% static "grids-responsive-min.css" %}">
    <link rel="stylesheet" href="{% static "blog.css" %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700" type="text/css">

    <link href="http://cdn.bootcss.com/highlight.js/8.0/styles/monokai_sublime.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/highlight.js/8.0/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>

    <style type="text/css">
        .codehilite {
            font-family: "Ubuntu Mono", monospace;
        }

        .pure-menu li {
            display: inline;
            position: relative;
        }

        #header-nav-list {
            margin-bottom: 1em;
        }
    </style>

    <script src="{% static "jquery.js" %}"></script>
    <script type="text/javascript">
        function construction_notice() {
            alert("Under Construction...>_<")
        }
    </script>

    {% block scripts %}
        {# We can use {{ block.super }} to get the block content in the super template. #}
    {% endblock %}
</head>

<body>
<div id="layout" class="pure-g">
    <div class="sidebar pure-u-1 pure-u-md-1-4">
        <div class="header">
            <h1 class="brand-title">Psrit's Blog</h1>
            <h2 class="brand-tagline">It's nice to see you!</h2>
            <nav class="nav" id="header-nav-list">
                <ul class="nav-list">
                    <li class="nav-item">
                        <a class="button-success pure-button" href="/">
                            主页
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="button-success pure-button"
                           href="{% url "archives" %}">
                            归档
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="button-success pure-button"
                           onclick="construction_notice()">
                            专题
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="button-success pure-button"
                           onclick="construction_notice()">
                            足迹
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="button-success pure-button"
                           onclick="construction_notice()"
                                {% comment %}href="{% url "about_me" %}"{% endcomment %}>
                            About Me
                        </a>
                    </li>
                    {#                    <li class="nav-item">#}
                    {#                        <a class="pure-button" href="https://github.com/psrit">Github</a>#}
                    {#                    </li>#}
                    {#                    <li class="nav-item">#}
                    {#                        <a class="pure-button" href="http://weibo.com/u/5054486665">Weibo</a>#}
                    {#                    </li>#}

                </ul>
            </nav>
            <form class="pure-form" action="{% url "article:search" %}" method="get">
                <input class="pure-input-rounded" type="text" name="search"
                       placeholder="Search" style="font-family: 'open sans', sans-serif; color: #3c3c3c"/>
            </form>
        </div>
    </div>

    <div class="content pure-u-1 pure-u-md-3-4">
        <div>
            {% block content %}
            {% endblock %}
            <div class="footer">
                <div class="pure-menu pure-menu-horizontal pure-menu-open">
                    <ul style="padding: 0 0 0 0; font-weight: 500">
                        <li class="pure-menu-item">
                            <a {% comment %}href="{% url "about_me" %}"{% endcomment %}
                                    onclick="construction_notice()"
                                    class="pure-menu-link">About Me</a>
                        </li>
                        <li class="pure-menu-item">
                            <a href="https://github.com/psrit" class="pure-menu-link">GitHub</a>
                        </li>
                        <li class="pure-menu-item">
                            <a href="http://weibo.com/u/5054486665"
                               class="pure-menu-link">Weibo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

templates/duoshuo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/home.html
{% extends "base.html" %}
{% load custom_markdown %}

{% block content %}
    <div class="posts">
        {% for post in post_list %}
            <section class="post">
                <header class="post-header">
                    <h2 class="post-title">
                        {{ post.title }}
                    </h2>

                    <p class="post-meta">
                        Time: <a class="post-author" href="#">{{ post.date_time }}</a>
                    </p>
                </header>

                <div class="post-description">
                    <p>
                        {{ post.content|custom_markdown|truncatewords_html:50 }}
                    </p>
                </div>
                <a class="pure-button" href="{% url "article:detail" post.id %}"> Read More >>> </a>

            </section>

            <hr/>
        {% endfor %}

        {% if post_list.object_list and post_list.paginator.num_pages > 1 %}
            <div>
                <ul class="pure-paginator" style="text-align:center; padding-top: 1.5em">
                    {% if post_list.has_previous %}
                        <li><a class="pure-button prev" href="?page={{ post_list.previous_page_number }}">
                            &#171;
                        </a></li>
                    {% endif %}
                    {#                    <li><a class="pure-button" href="#">1</a></li>#}

                    <li><a class="pure-button pure-button-active" href="#">
                        {{ post_list.number }} / {{ post_list.paginator.num_pages }}
                    </a></li>

                    {% if post_list.has_next %}
                        <li><a class="pure-button next" href="?page={{ post_list.next_page_number }}">
                            &#187;
                        </a></li>
                    {% endif %}
                </ul>
            </div>
        {% endif %}
{% endblock %}

templates/home_1.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Blogs</h2>
                {#                <h3 class="section-subheading text-muted"></h3>#}
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <ul class="timeline">
                    {% for post in post_list %}
                        <li>
                            <div class="timeline-image">
                                <img class="img-circle img-responsive" src="{% static "img/about/1.jpg" %}" alt="">
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h4>{{ post.date_time }}</h4>
                                    <h4 class="subheading">{{ post.title }}</h4>
                                </div>
                                <div class="timeline-body">
                                    <p class="text-muted">{{ post.content }}</p>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/post.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load custom_markdown %}

{% block content %}
    <div class="posts">
        <section class="post">
            <header class="post-header">
                <h2 class="post-title">{{ post.title }}</h2>
                <p class="post-meta">
                    Time: <a class="post-author" href="#">{{ post.date_time|date:"Y / m / d" }}</a>
                    {% for category in post.categories.all %}
                        <a class="post-category post-category-js"
                           href="{% url "search_tag" category.name %}">
                            {{ category.name }}
                        </a>
                    {% endfor %}
                </p>
            </header>

            <div class="post-description">
                <p>
                    {{ post.content|custom_markdown }}
                </p>
            </div>
        </section>
    </div><!-- /.blog-post -->
{% endblock %}

templates/search.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="posts">
        <header class="post-header category_flip">
            <h2 class="post-title">
                Search Results
            </h2>
        </header>
        {% if having_articles %}
            <div>
                {% for article in article_set.all %}
                    <div>
                        <a href="{% url "article:detail" article.id %}">
                            {{ article.title }}
                        </a>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            {% comment %}
                If there are no articles found in search_blog (set having_articles=False,
                the logical process come into this case.
            {% endcomment %}
            <div>
                No articles found. :(
            </div>
        {% endif %}
    </div>
{% endblock %}